In [3]:
# import the load_boston() function from sklearn.datasets
from sklearn.datasets import load_boston
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import itertools


import keras
import matplotlib.pyplot as plt #This package is for plotting
%matplotlib inline  
import numpy as np
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Input, Dropout
from keras.optimizers import SGD
from keras.initializers import RandomNormal
from keras.models import load_model


boston = load_boston()

bos = pd.DataFrame(boston.data)
bos.columns = boston.feature_names
bos['PRICE'] = boston.target

bos.head()

Using TensorFlow backend.


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  PRICE  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [4]:
X_train, X_test, y_train, y_test = train_test_split(bos[boston.feature_names], bos['PRICE'], test_size=0.25, random_state=0)

basic_reg = LinearRegression()
basic_reg.fit(X_train, y_train)

y_pred = basic_reg.predict(X_test)
print('MSE from test data compared to prediction')
print(mean_squared_error(y_test, y_pred))
print('R^2 from test data compared to prediction')
print(r2_score(y_test, y_pred))


MSE from test data compared to prediction
29.782245092302336
R^2 from test data compared to prediction
0.6354638433202133


In [5]:
inp = Input(shape=(13,))
output = Dense(1)(inp)
model = keras.models.Model(input=inp, output=output)
model.compile(optimizer='adam', loss='mse', metrics=["mse"])
model.fit(X_train, y_train, epochs=200, batch_size=1, verbose=1)

/Users/johnminer/Library/Python/3.7/lib/python/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=Tensor("de...)`
  This is separate from the ipykernel package so we can avoid doing imports until


Epoch 1/200
379/379 [==============================] - 0s 742us/step - loss: 7173.6511 - mse: 7173.6538
Epoch 2/200
379/379 [==============================] - 0s 550us/step - loss: 334.7064 - mse: 334.7064
Epoch 3/200
379/379 [==============================] - 0s 520us/step - loss: 284.1626 - mse: 284.1627
Epoch 4/200
379/379 [==============================] - 0s 628us/step - loss: 247.4893 - mse: 247.4894
Epoch 5/200
379/379 [==============================] - 0s 620us/step - loss: 223.0686 - mse: 223.0687
Epoch 6/200
379/379 [==============================] - 0s 652us/step - loss: 195.5531 - mse: 195.5531
Epoch 7/200
379/379 [==============================] - 0s 557us/step - loss: 171.6611 - mse: 171.6611
Epoch 8/200
379/379 [==============================] - 0s 504us/step - loss: 150.2776 - mse: 150.2776
Epoch 9/200
379/379 [==============================] - 0s 595us/step - loss: 131.8475 - mse: 131.8475
Epoch 10/200
379/379 [==============================] - 0s 628us/step - loss: 11

Epoch 82/200
379/379 [==============================] - 0s 526us/step - loss: 34.2991 - mse: 34.2991
Epoch 83/200
379/379 [==============================] - 0s 508us/step - loss: 34.7317 - mse: 34.7317
Epoch 84/200
379/379 [==============================] - 0s 495us/step - loss: 33.5389 - mse: 33.5389
Epoch 85/200
379/379 [==============================] - 0s 499us/step - loss: 34.5359 - mse: 34.5359
Epoch 86/200
379/379 [==============================] - 0s 503us/step - loss: 34.2432 - mse: 34.2433
Epoch 87/200
379/379 [==============================] - 0s 510us/step - loss: 33.3008 - mse: 33.3008
Epoch 88/200
379/379 [==============================] - 0s 533us/step - loss: 33.5110 - mse: 33.5110
Epoch 89/200
379/379 [==============================] - 0s 519us/step - loss: 34.0610 - mse: 34.0610
Epoch 90/200
379/379 [==============================] - 0s 516us/step - loss: 33.7757 - mse: 33.7757
Epoch 91/200
379/379 [==============================] - 0s 508us/step - loss: 33.0482 - mse

379/379 [==============================] - 0s 508us/step - loss: 26.4963 - mse: 26.4963
Epoch 163/200
379/379 [==============================] - 0s 511us/step - loss: 26.6820 - mse: 26.6820
Epoch 164/200
379/379 [==============================] - 0s 509us/step - loss: 28.3599 - mse: 28.3599
Epoch 165/200
379/379 [==============================] - 0s 573us/step - loss: 27.2351 - mse: 27.2351
Epoch 166/200
379/379 [==============================] - 0s 521us/step - loss: 28.1809 - mse: 28.1809
Epoch 167/200
379/379 [==============================] - 0s 506us/step - loss: 27.7335 - mse: 27.7334
Epoch 168/200
379/379 [==============================] - 0s 513us/step - loss: 28.4392 - mse: 28.4392
Epoch 169/200
379/379 [==============================] - 0s 495us/step - loss: 26.7107 - mse: 26.7107
Epoch 170/200
379/379 [==============================] - 0s 502us/step - loss: 27.1508 - mse: 27.1508
Epoch 171/200
379/379 [==============================] - 0s 495us/step - loss: 27.8750 - mse: 27

In [6]:
model.fit(X_train, y_train, epochs=200, batch_size=1, verbose=1)

Epoch 1/200
379/379 [==============================] - 0s 550us/step - loss: 25.7332 - mse: 25.7332
Epoch 2/200
379/379 [==============================] - 0s 575us/step - loss: 26.6036 - mse: 26.6036
Epoch 3/200
379/379 [==============================] - 0s 545us/step - loss: 25.5830 - mse: 25.5830
Epoch 4/200
379/379 [==============================] - 0s 578us/step - loss: 27.2026 - mse: 27.2026
Epoch 5/200
379/379 [==============================] - 0s 593us/step - loss: 25.6281 - mse: 25.6281
Epoch 6/200
379/379 [==============================] - 0s 628us/step - loss: 25.9538 - mse: 25.9538
Epoch 7/200
379/379 [==============================] - 0s 614us/step - loss: 26.1662 - mse: 26.1662
Epoch 8/200
379/379 [==============================] - 0s 592us/step - loss: 27.2120 - mse: 27.2120
Epoch 9/200
379/379 [==============================] - 0s 567us/step - loss: 27.0708 - mse: 27.0708
Epoch 10/200
379/379 [==============================] - 0s 525us/step - loss: 25.4934 - mse: 25.4934

379/379 [==============================] - 0s 526us/step - loss: 24.1142 - mse: 24.1142
Epoch 83/200
379/379 [==============================] - 0s 540us/step - loss: 25.1997 - mse: 25.1997
Epoch 84/200
379/379 [==============================] - 0s 503us/step - loss: 24.7796 - mse: 24.7796
Epoch 85/200
379/379 [==============================] - 0s 514us/step - loss: 24.9636 - mse: 24.9636
Epoch 86/200
379/379 [==============================] - 0s 497us/step - loss: 24.2685 - mse: 24.2685
Epoch 87/200
379/379 [==============================] - 0s 506us/step - loss: 24.6342 - mse: 24.6342
Epoch 88/200
379/379 [==============================] - 0s 513us/step - loss: 24.8270 - mse: 24.8270
Epoch 89/200
379/379 [==============================] - 0s 519us/step - loss: 24.7158 - mse: 24.7158
Epoch 90/200
379/379 [==============================] - 0s 513us/step - loss: 25.3372 - mse: 25.3372
Epoch 91/200
379/379 [==============================] - 0s 501us/step - loss: 23.7580 - mse: 23.7580
Epo

379/379 [==============================] - 0s 526us/step - loss: 24.2790 - mse: 24.2790
Epoch 163/200
379/379 [==============================] - 0s 502us/step - loss: 23.9992 - mse: 23.9992
Epoch 164/200
379/379 [==============================] - 0s 526us/step - loss: 25.2181 - mse: 25.2181
Epoch 165/200
379/379 [==============================] - 0s 506us/step - loss: 25.0245 - mse: 25.0246
Epoch 166/200
379/379 [==============================] - 0s 511us/step - loss: 24.6681 - mse: 24.6681
Epoch 167/200
379/379 [==============================] - 0s 515us/step - loss: 24.1548 - mse: 24.1548
Epoch 168/200
379/379 [==============================] - 0s 525us/step - loss: 25.0535 - mse: 25.0535
Epoch 169/200
379/379 [==============================] - 0s 512us/step - loss: 24.5951 - mse: 24.5951
Epoch 170/200
379/379 [==============================] - 0s 506us/step - loss: 24.3871 - mse: 24.3871
Epoch 171/200
379/379 [==============================] - 0s 505us/step - loss: 24.1887 - mse: 24

In [7]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=1)

127/127 [==============================] - 0s 238us/step


In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
pima = pd.read_csv('diabetes.csv')

feature_cols = ['Pregnancies', 'Insulin', 'BMI', 'Age']
X = pima[feature_cols]
y = pima['Outcome']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

y_pred = log_reg.predict(X_test)


/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [29]:
y_test = list(y_test)
y_pred = list(y_pred)
def confusion(yt, yp):
    ma = np.zeros((2,2))
    for i in range(len(yt)):
        if yt[i] == yp[i] and yp[i] == 0:
            ma[0][0] += 1
        elif yt[i] == yp[i] and yp[i] == 1:
            ma[1][1] += 1
        elif yt[i] != yp[i] and yp[i] == 0:
            ma[1][0] += 1
        elif yt[i] != yp[i] and yp[i] == 1:
            ma[0][1] += 1
    return ma

In [30]:
print(confusion(y_test, y_pred))

[[118.  12.]
 [ 47.  15.]]


In [34]:
inp = Input(shape=(4,))
output = Dense(1)(inp)
model = keras.models.Model(input=inp, output=output)
model.compile(optimizer='adam', loss='mse', metrics=["mse"])
model.fit(X_train, y_train, epochs=12, batch_size=1, verbose=1)

/Users/johnminer/Library/Python/3.7/lib/python/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=Tensor("de...)`
  This is separate from the ipykernel package so we can avoid doing imports until


Epoch 1/12
576/576 [==============================] - 0s 631us/step - loss: 4298.0836 - mse: 4298.0791
Epoch 2/12
576/576 [==============================] - 0s 504us/step - loss: 1964.5310 - mse: 1964.5321
Epoch 3/12
576/576 [==============================] - 0s 502us/step - loss: 1044.5243 - mse: 1044.5238
Epoch 4/12
576/576 [==============================] - 0s 494us/step - loss: 590.3631 - mse: 590.3629
Epoch 5/12
576/576 [==============================] - 0s 505us/step - loss: 336.6076 - mse: 336.6075
Epoch 6/12
576/576 [==============================] - 0s 534us/step - loss: 203.5441 - mse: 203.5441
Epoch 7/12
576/576 [==============================] - 0s 539us/step - loss: 137.0325 - mse: 137.0324
Epoch 8/12
576/576 [==============================] - 0s 546us/step - loss: 102.0529 - mse: 102.0529
Epoch 9/12
576/576 [==============================] - 0s 502us/step - loss: 79.6760 - mse: 79.6760
Epoch 10/12
576/576 [==============================] - 0s 515us/step - loss: 61.4017 - 

In [37]:
model.fit(X_train, y_train, epochs=100, batch_size=1, verbose=1)

Epoch 1/100
576/576 [==============================] - 0s 553us/step - loss: 22.7127 - mse: 22.7127
Epoch 2/100
576/576 [==============================] - 0s 525us/step - loss: 14.9239 - mse: 14.9239
Epoch 3/100
576/576 [==============================] - 0s 532us/step - loss: 9.2947 - mse: 9.2947
Epoch 4/100
576/576 [==============================] - 0s 517us/step - loss: 5.5005 - mse: 5.5005
Epoch 5/100
576/576 [==============================] - 0s 622us/step - loss: 3.1134 - mse: 3.1134
Epoch 6/100
576/576 [==============================] - 0s 626us/step - loss: 1.7148 - mse: 1.7148
Epoch 7/100
576/576 [==============================] - 0s 512us/step - loss: 0.9874 - mse: 0.9874
Epoch 8/100
576/576 [==============================] - 0s 507us/step - loss: 0.5432 - mse: 0.5432
Epoch 9/100
576/576 [==============================] - 0s 513us/step - loss: 0.3515 - mse: 0.3515
Epoch 10/100
576/576 [==============================] - 0s 600us/step - loss: 0.2618 - mse: 0.2618
Epoch 11/100
57

576/576 [==============================] - 0s 552us/step - loss: 0.2291 - mse: 0.2291
Epoch 84/100
576/576 [==============================] - 0s 541us/step - loss: 0.2455 - mse: 0.2455
Epoch 85/100
576/576 [==============================] - 0s 541us/step - loss: 0.2644 - mse: 0.2644
Epoch 86/100
576/576 [==============================] - 0s 516us/step - loss: 0.2591 - mse: 0.2591
Epoch 87/100
576/576 [==============================] - 0s 521us/step - loss: 0.2731 - mse: 0.2731
Epoch 88/100
576/576 [==============================] - 0s 504us/step - loss: 0.2600 - mse: 0.2600
Epoch 89/100
576/576 [==============================] - 0s 516us/step - loss: 0.2275 - mse: 0.2275
Epoch 90/100
576/576 [==============================] - 0s 501us/step - loss: 0.2461 - mse: 0.2461
Epoch 91/100
576/576 [==============================] - 0s 523us/step - loss: 0.2412 - mse: 0.2412
Epoch 92/100
576/576 [==============================] - 0s 524us/step - loss: 0.2959 - mse: 0.2959
Epoch 93/100
576/576 [=

In [39]:
y_pred = model.predict(X_test)

In [44]:
print(confusion(y_test, [1 if i >= 0.90 else 0 for i in y_pred]))

[[129.   1.]
 [ 56.   6.]]


In [40]:
y_pred

array([[ 0.32557607],
       [ 0.37258834],
       [ 0.24573225],
       [ 0.62197214],
       [ 0.08149844],
       [ 0.14763182],
       [ 0.6767823 ],
       [ 0.6886373 ],
       [ 0.5993183 ],
       [ 0.88277453],
       [ 0.64500827],
       [ 0.97931474],
       [ 0.3432216 ],
       [ 0.33115858],
       [ 0.39170069],
       [ 0.13218516],
       [ 0.5881848 ],
       [-0.00219673],
       [ 0.4223187 ],
       [ 0.44146556],
       [ 0.40451342],
       [ 0.3323722 ],
       [ 0.13559955],
       [ 0.38919288],
       [ 0.2541324 ],
       [ 0.20400685],
       [-0.047144  ],
       [ 0.82452196],
       [ 0.06558126],
       [ 0.16679496],
       [ 0.5829057 ],
       [ 0.40435708],
       [ 0.31288862],
       [ 0.55230635],
       [ 0.09592575],
       [ 0.3570487 ],
       [ 0.6024062 ],
       [ 0.17194605],
       [ 0.33859897],
       [ 0.36189443],
       [ 0.35150504],
       [ 0.34313697],
       [ 0.30451512],
       [ 0.24624419],
       [ 1.3165178 ],
       [-0