In [1]:
import numpy as np

In [2]:
X = np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
y = np.array([[1],[1],[0]])

In [17]:
class my_network():
    def __init__(self):
        self.weights = np.array([[np.random.rand(3) for i in range(4)], [np.random.rand(3)]])
        self.biases = np.array([np.random.rand(3), np.random.rand(1)])
    
    def predict(self, ls_inputs):
        prediction = []
        for item in ls_inputs:
            pred = item[:,None]
            for weight, bias in zip(self.weights, self.biases):
                pred = np.dot(weights[weight], pred) + bias[:,None]
            prediction.append(pred)
        return np.array(prediction)
                
    
    def sigmoid(self, number):
        return 1/(1+(2.718**number))

    def mse_function(self, ls1, ls2):
        return sum([(ls1[i]-ls2[i])**2 for i in range(len(ls1))])
    
    def back_prop(self, pred, actual):
        mses = []
        for i in range(len(pred)):
            mses.append(pred[i], actual[i])
        mean_mse = np.mean(mses)
        for weight in range(len(self.weights)):
            
            for line in range(len(weight)):
                self.weight[weight][line]
            
        

IndentationError: expected an indented block (<ipython-input-17-57840563f54f>, line 10)

In [65]:
weights = np.array([[np.random.rand(4) for i in range(3)]])
biases = np.array([np.random.rand(3), np.random.rand(1)])

In [66]:
np.dot(weights[0], X[0][:,None]) + biases[0][:,None]

array([[1.36867646],
       [1.92082055],
       [2.10023338]])

In [58]:
weights

array([[[0.6300729 , 0.05001952, 0.44123161, 0.40325779],
        [0.21606831, 0.30343246, 0.18304949, 0.53273873],
        [0.42347936, 0.0945498 , 0.46559401, 0.37078484]]])

In [59]:
X[0][:,None]

array([[1],
       [0],
       [1],
       [0]])